const CSS_HANDLES = [
  'banner-general-container',
  'banner__general-container',
  'banner__general-container--image',
  'banner__general-container-top',
  'banner__general-container-top--image',
  'countdown__general-container-slider',
  'countdown__title-slider',
  'countdown__title-text-slider',
  'countdown__time-container-slider',
  'time-container__box-slider',
  'time-container__box-time-slider',
  'time-container__box-time-slider--time',
  'time-container__box-text-slider',
  'time-container__box-text-slider--text',
  'alineacion-izquierda-abajo-slider',
  'alineacion-centro-abajo-slider',
  'alineacion-derecha-abajo-slider',
  'countdown__general-container-top',
  'countdown__title-top',
  'countdown__title-text-top',
  'countdown__time-container-top',
  'time-container__box-top',
  'time-container__box-time-top',
  'time-container__box-time-top--time',
  'time-container__box-text-top',
  'time-container__box-text-top--text',
  'alineacion-izquierda',
  'alineacion-centro',
  'alineacion-derecha',
  'simple-banner__container',
  'simple-banner__image'
]

export default CSS_HANDLES;
